openapi: 3.0.3
info:
  title: Food API
  description: API for managing food-related operations
  contact:
    name: Gustavo
    email: gustavosantana559@gmail.com
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1
    description: Development server

paths:
  /auth/register:
    post:
      summary: Create a new user
      description: Create a new user in the system
      operationId: createUser
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "201":
          description: User created successfully!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"

components:
  schemas:
    User:
      type: object
      properties:
        userName:
          type: string
          example: "Jennifer Lynston"
        email:
          type: string
          example: "jennylyn@gmail.com"
        password:
          type: string
          example: "jejen22"
        phone:
          type: string
          example: "991-408-0762"
        address:
          type: array
          items:
            type: string
          example: ["Lorena Brook", "Chicago", "USA"]
        answer:
          type: string
          example: "cat"
